import NavBar from '@/components/NavBar'
import './globals.css'

import { Poppins } from 'next/font/google'
import { Bebas_Neue } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: '400', variable: '--font-poppins' })
const bebas = Bebas_Neue({ subsets: ['latin'], weight: '400', variable: '--font-bebas' })

export const metadata = {
  title: 'Iron Gym',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${bebas.variable} font-poppins bg-home bg-cover bg-no-repeat bg-top bg-fixed overflow-x-hidden`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
